package rems.idea.mixincompletion.template;

import com.demonwav.mcdev.MinecraftSettings;
import com.demonwav.mcdev.creator.custom.TemplateDescriptor;
import com.demonwav.mcdev.creator.custom.TemplateFile;
import com.demonwav.mcdev.creator.custom.TemplatePropertyDescriptor;
import com.demonwav.mcdev.creator.custom.providers.LoadedTemplate;
import com.demonwav.mcdev.creator.custom.providers.TemplateProvider;
import com.demonwav.mcdev.creator.custom.providers.VfsLoadedTemplate;
import com.intellij.ide.util.projectWizard.WizardContext;
import com.intellij.notification.Notification;
import com.intellij.notification.NotificationGroupManager;
import com.intellij.notification.NotificationType;
import com.intellij.notification.Notifications;
import com.intellij.openapi.vfs.VirtualFile;
import kotlin.Unit;
import kotlin.coroutines.Continuation;
import kotlin.jvm.functions.Function1;
import org.jetbrains.annotations.NotNull;

import javax.swing.JComponent;
import java.util.Collection;
import java.util.List;
import java.util.Map;

/**
 * The multi-version template, offered in the Minecraft project wizard.
 *
 * <p>What the platform's own templates do not cover is a project that builds against several Minecraft
 * versions at once. That project is not one directory of sources but a layout: a directory per version under
 * {@code versions/}, each carrying the properties that version is built with, plus a shared source tree that
 * all of them compile. The wizard has no way to express "these versions and no others" in the file list it
 * takes, so the files are not declared here at all - the template is generated by a finalizer, which has the
 * chosen versions in hand and can lay the repository out accordingly.
 *
 * <p>What is declared here is what the reader is asked: the two ends of the version range.
 */
public final class MultiVersionTemplateProvider implements TemplateProvider {
    /** The key this provider is registered under, and the one a repository entry has to name to reach it. */
    static final String KEY = "liuyue_multi_version";

    /** What the template is called in the wizard. */
    static final String LABEL = "多版本 Fabric";

    /** The repository the template is built from, when the entry does not name one. */
    static final String REPOSITORY = "liuyuexiaoyu1/fabric-mod-template";

    /** The properties the reader fills in, and the names the finalizer reads them back under. */
    static final String FROM_VERSION = "minecraftVersionFrom";
    static final String TO_VERSION = "minecraftVersionTo";

    /** The finalizer type that turns the repository into a project, registered by this plugin. */
    static final String FINALIZER = "liuyue_template";

    /** Where a failed fetch is reported, registered by the plugin descriptor. */
    private static final String NOTIFICATION_GROUP = "Preprocessor Template";

    /** The format version the descriptor is written against; the plugin refuses anything newer. */
    private static final int FORMAT_VERSION = 1;

    @Override
    public @NotNull String getLabel() {
        return LABEL;
    }

    @Override
    public boolean getHasConfig() {
        return false;
    }

    @Override
    public Object loadTemplates(@NotNull WizardContext context, @NotNull MinecraftSettings.TemplateRepo repo,
                                @NotNull Continuation<? super Collection<? extends LoadedTemplate>> continuation) {
        // The repository the entry names, which is the one the reader is looking at. Only when it names none
        // is the default used, so a second entry can point somewhere else without a second provider.
        String data = repo.getData();
        String repository = data == null || data.isBlank() ? REPOSITORY : data;
        VirtualFile root = TemplateRepository.root(repository);

        // Nothing is offered when the repository could not be read, and the wizard says so in a way that names
        // no reason: an empty list is what it shows for a repository that is unreachable, for one that was
        // renamed, and for a wrong branch alike. The reason is written where it can be read - a log is not
        // somewhere a reader looks in the middle of filling in a form.
        if (root == null) {
            notifyUnreachable(repository);

            return List.of();
        }

        // Answered rather than suspended. A Kotlin suspend function that finishes without suspending hands its
        // value back through the return; the continuation is the caller's, and is not to be touched. This used
        // to resume it as well and return Unit - both answers to the same question - and the wizard read the
        // return: "class kotlin.Unit cannot be cast to class java.util.Collection", a template list that was
        // never set, and a blank panel under 多版本 Fabric.
        return List.of(new VfsLoadedTemplate(root, getLabel(), tooltip(), descriptor(root), true));
    }

    /** Says out loud that the repository could not be fetched, and where the details are. */
    private static void notifyUnreachable(String repository) {
        Notification notification = NotificationGroupManager.getInstance()
                .getNotificationGroup(NOTIFICATION_GROUP)
                .createNotification("取不到模板仓库 " + repository,
                        "已在日志里记下试过的地址（Help → Show Log in Explorer，搜索 preprocessor template）。"
                                + "若是网络或代理问题，IDE 的代理设置在 Settings → Appearance & Behavior → "
                                + "System Settings → HTTP Proxy。",
                        NotificationType.WARNING);

        Notifications.Bus.notify(notification);
    }

    @Override
    public JComponent setupConfigUi(@NotNull String config, @NotNull Function1<? super String, Unit> onChanged) {
        return null;
    }

    private static String tooltip() {
        return "构建于多个 Minecraft 版本的 Fabric 项目："
                + "按范围选择版本，每个版本一个目录，共用一套源码。"
                + "preprocessor 的版本取 jitpack 上的最新构建。";
    }

    /**
     * What the template declares.
     *
     * <p>No files: the layout depends on the version range that is chosen, and the file list is fixed when the
     * descriptor is built. The finalizer writes them instead, from the same repository this provider read.
     *
     * <p>The two ends of the range are offered as the versions the repository has, not as a box to type one
     * into. Every version the wizard can build is a version that repository holds, so the list is not a
     * suggestion about what may be typed - it is the whole of what there is, and it is read from the same
     * settings file the build is generated from. A version typed by hand and a version that happens to exist
     * look the same on screen, so the difference was found later, in the build.
     */
    private static TemplateDescriptor descriptor(VirtualFile root) {
        List<String> versions = TemplateRepository.versions(root);

        List<TemplatePropertyDescriptor> properties = List.of(
                version(FROM_VERSION, "起始版本", "例如 1.20.1，留空则从仓库支持的第一个版本开始", 0, versions),
                version(TO_VERSION, "结束版本", "例如 1.21.5，留空则到仓库支持的最后一个版本", 1, versions));

        List<TemplateFile> files = List.of();
        List<Map<String, Object>> finalizers = List.of(Map.of("type", FINALIZER));

        return new TemplateDescriptor(FORMAT_VERSION, "多版本 Fabric", "fabric", null, false,
                properties, files, finalizers);
    }

    /**
     * One end of the version range.
     *
     * <p>With the repository's versions behind it this is a list to choose from: the wizard draws a property
     * that has options as a dropdown when there are more of them than fit in a row, and {@code forceDropdown}
     * keeps it a dropdown however few there are. A repository whose version list could not be read leaves the
     * property a plain field rather than an empty list - there is nothing to choose from, and typing a version
     * is then the only thing left to do.
     */
    private static TemplatePropertyDescriptor version(String name, String label, String hint, int order,
                                                      List<String> versions) {
        return versions.isEmpty()
                ? text(name, label, hint, order)
                : choice(name, label, hint, order, versions);
    }

    private static TemplatePropertyDescriptor choice(String name, String label, String hint, int order,
                                                     List<String> options) {
        return new TemplatePropertyDescriptor(
                name,           // name
                "string",       // type
                label,          // label
                order,          // order
                options,        // options
                null,           // limit
                null,           // maxSegmentedButtonsCount
                Boolean.TRUE,   // forceDropdown
                null,           // groupProperties
                null,           // remember
                null,           // visible
                null,           // forceValue
                null,           // editable
                null,           // collapsible
                hint,           // warning
                null,           // default
                null,           // nullIfDefault
                null,           // derives
                null,           // inheritFrom
                null,           // parameters
                null);          // validator
    }

    /**
     * A property the reader types into.
     *
     * <p>Every position has to be named: Kotlin's defaults are filled in by the compiler rather than by the
     * JVM, so a Java caller has to supply all of them. They are named in the order the wizard plugin this is
     * built against declares them, which is not the order an older release declared: a field was added after
     * {@code visible}, and everything past it moved along by one. Written against the older order, the hint
     * landed on a field of another type - NoSuchMethodError on the first property, an empty template list,
     * and the wizard showing its one sentence for that, "There are no templates available". The build now
     * pins that plugin's version, so the order here is the order that will be there.
     */
    private static TemplatePropertyDescriptor text(String name, String label, String hint, int order) {
        return new TemplatePropertyDescriptor(
                name,           // name
                "string",       // type
                label,          // label
                order,          // order
                null,           // options
                null,           // limit
                null,           // maxSegmentedButtonsCount
                null,           // forceDropdown
                null,           // groupProperties
                null,           // remember
                null,           // visible
                null,           // forceValue
                null,           // editable
                null,           // collapsible
                hint,           // warning
                null,           // default
                null,           // nullIfDefault
                null,           // derives
                null,           // inheritFrom
                null,           // parameters
                null);          // validator
    }
}
